const gameTypes = {
  START_FETCHING: "START_FETCHING",
  REQUEST_SUCCESS: "REQUEST_SUCCESS",
  REQUEST_FAIL: "REQUEST_FAIL",
  FILTER_PLANETS: "FILTER_PLANETS",
  DISABLE_CORRESPONDING_VEHICLES: "DISABLE_CORRESPONDING_VEHICLES",
  DECREMENT_VEHICLE_COUNT: "DECREMENT_VEHICLE_COUNT",
  UPDATE_RESULT:"UPDATE_RESULT",
  RESET_GAME:"RESET_GAME"
};

export default gameTypes;
